version = 0.1
[default.deploy.parameters]
stack_name = "workshop"
resolve_s3 = true
s3_prefix = "workshop"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "GenExamImageUri=\"exam-gen-workshop\" TakeExamImageUri=\"exam-gen-workshop\" CPUArchitecture=\"arm64\""
image_repositories = []
